AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:

  NamePrefix:
    Type: String

Globals:

  Function:
    Runtime: nodejs8.10
    Timeout: 15
    MemorySize: 256

Resources:

  NodeModulesLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: NodeModulesLayer
      ContentUri: dependencies
      CompatibleRuntimes:
        - nodejs8.10
      RetentionPolicy: Retain

  GetSecretsValueFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: GetSecretsValueFunction
      CodeUri: src/
      Handler: index.handler
      Tracing: Active
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${NamePrefix}/*'
      Environment:
        Variables:
          SECRET_NAME: !Ref NamePrefix
      Layers:
        - !Ref NodeModulesLayer
      Events:
        Warmup:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Name: Warmup
            Enabled: false
