AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:

  NamePrefix:
    Type: String
  LayerName:
    Type: String
    Default: NodeModulesLayer
  LayerVersion:
    Type: Number
    Default: 2

Resources:

  GetSecretsValueFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: GetSecretsValueFunction
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs8.10
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/${NamePrefix}/*'
      Environment:
        Variables:
          SECRET_NAME: !Ref NamePrefix
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:layer:${LayerName}:${LayerVersion}

  NodeModulesLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: !Ref LayerName
      ContentUri: layer_modules
      CompatibleRuntimes:
        - nodejs8.10
      RetentionPolicy: Retain
